/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function cloneFileExclusive(sourceFd: number, targetRootFd: number, targetRelPath: string): number

export declare function copyFileRangeExclusive(sourceFd: number, targetRootFd: number, targetRelPath: string): Promise<NativeCopyResult>

export declare function createPrivateDirectory(path: string): void

export declare function extractArchiveNative(path: string, kind: string, rootFd: number, plan: Array<NativeArchivePlanEntry>, maxMetaEntryBytes: number, signal: AbortSignal): Promise<void>

export interface FileHash {
  bytes: number
  digest: string
}

export interface FileIdentity {
  dev: number
  ino: number
  mode: number
  nlink: number
  size: number
  isFile: boolean
  isDirectory: boolean
  isSymbolicLink: boolean
}

export declare function fstatIdentity(fd: number): FileIdentity

export declare function inspectArchiveNative(path: string, kind: string, maxEntries: number, maxMetaEntryBytes: number, maxManifestBytes: number, signal: AbortSignal): Promise<Array<NativeArchiveEntry>>

export declare function linkBeneath(sourceRootFd: number, sourceRelPath: string, targetRootFd: number, targetRelPath: string): void

export declare function mkdirBeneath(rootFd: number, relPath: string, mode: number): void

export interface NativeArchiveEntry {
  index: number
  path: string
  kind: string
  size: number
  mode: number
}

export interface NativeArchivePlanEntry {
  index: number
  path: string
  kind: string
  size: number
  mode: number
}

export interface NativeCopyResult {
  fd: number
  bytes: number
  errorCode?: string
  errorMessage?: string
}

export declare function openBeneath(rootFd: number, relPath: string, flags: number): OpenBeneathResult

export interface OpenBeneathResult {
  fd: number
  containment: 'kernel-atomic' | 'best-effort'
}

export declare function readArchiveEntryNative(path: string, kind: string, requested: string, maxBytes: number, maxEntries: number, maxMetaEntryBytes: number, signal: AbortSignal): Promise<Buffer>

export declare function readOwnerAndDacl(path: string): WindowsSecurityFacts

export declare function renameNoReplace(sourceRootFd: number, sourceRelPath: string, targetRootFd: number, targetRelPath: string): void

export declare function sha256File(fd: number): Promise<FileHash>

export interface WindowsAccessControlEntry {
  sid: string
  mask: number
  aceType: string
  flags: WindowsAceFlags
}

export interface WindowsAceFlags {
  raw: number
  objectInherit: boolean
  containerInherit: boolean
  noPropagateInherit: boolean
  inheritOnly: boolean
  inherited: boolean
  successfulAccess: boolean
  failedAccess: boolean
}

export interface WindowsSecurityFacts {
  ownerSid: string
  currentUserSid: string
  ownerClass: string
  worldWritable: boolean
  groupWritable: boolean
  worldReadable: boolean
  groupReadable: boolean
  fallbackRequired: boolean
  daclPresent: boolean
  isLocal: boolean
  aceListComplete: boolean
  unsupportedAceTypes: Array<number>
  aces: Array<WindowsAccessControlEntry>
}
