[package]
name = "fs-safe-archive-wasm"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
publish = false
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
bzip2 = "0.6.1"
fs-safe-archive-core = { path = "../archive-core" }
ruzstd = { path = "../vendor/ruzstd-0.9.0", version = "0.9.0" }
