[package]
name = "fs-safe-archive-wasm"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
publish = false
license = "MIT"

[lib]
crate-type = ["cdylib"]

[features]
allocator-tests = []

[dependencies]
fs-safe-archive-core = { path = "../archive-core" }
libbz2-rs-sys = { version = "0.2.5", default-features = false, features = ["rust-allocator"] }
zstd-sys = { version = "2.1.0", default-features = false, features = ["experimental"] }

[dev-dependencies]
bzip2 = "0.6.1"
zstd = { version = "0.14.0", default-features = false }
