// Synthetic fixtures from archive-gnu.ts, compressed with Node zstd and Python bz2.
// Precompressed so tests do not require external compressors or Node zstd support.
export const compressedGnu: Record<string, Record<"tar-zstd" | "tar-bzip2", string>> = {
  "L empty": {
    "tar-zstd": "KLUv/WAADdUDAKKEDxaQJeqIwFbYSr4P/ki3MfaGz4BFVUdl6x2KgAhz1IJyifQMfy5rRioaIBGmmHKdGgheJ80zv/+PmP8NrMUCFAD9cxXAB6oeGzCrCmQeIBzbYCJgQGUg8wDZsQZMmglUCANEChCggHhDagBIx63wUxsAx8pleAJa",
    "tar-bzip2": "QlpoOTFBWSZTWVrumqsAAHRfgMmAQAH3AEAECAZird+ACCggAHIZUNqAAAaNAzUEkUyQB6J6h5QMBKfM+N7BtCro3CA7X3YJ1zFN5ByW8XBkhwTLacyZEQRTCSpWsAUmUbmKMSkqRBnhZanFlfLUBg86wcGj50U6+wfLMGFKCpVSxKSR+LuSKcKEgtd01Vg="
  },
  "L NUL-only": {
    "tar-zstd": "KLUv/WAAD+UDAKKEDxaAJ+pIMIyUhv7obNCqde8QBnDAjA4Z6wWUARHmqAfl0ug5b0xZA6SiCRJRSCHXqQLh9dE88/v/iPnfwVosFQD9cxXAB6oeGwBUFcgMHNtgon6gAjCgMpB5gOxYAybNBCqEASIFCFBAvCE1AKTjVvipDYBj5TI8AS0=",
    "tar-bzip2": "QlpoOTFBWSZTWXd7EL4AAHjfgMmAQAH3AEAECAZird+ACiggAHIjVA9Q0aABo0DanqDaimUGTR5Go9JpoA0r292qbLUg+VgtqBLCc/A5wRi+Mi43otYQ6QxrSioooSiMgOlcoJFzEZsqtg0pEIpM8LDEZNr4dMQSA0R5OL18VH3iQOcpQrAoVQw6gQ/F3JFOFCQd3sQvgA=="
  },
  "L embedded NUL suffix": {
    "tar-zstd": "KLUv/WAAD2UEAJIFExmAOenoN0fEFguEjxq4qNK/LTokvYCg0SsD2RiU4o7DjxdqWYkgSeGYNQeKSUYR4FEAVVlJIqxDEhw7dheVYJpuFEf8/v8d/heRqQQVAP1zFcAHqh4bAFQ1kBHG4PdrGt6BqsCAyoGMA+QxGDBpJlAhDBApQIAC4g2pASAdt8JPbQAcK5fhCWgB",
    "tar-bzip2": "QlpoOTFBWSZTWc3QqooAAH9fgcuAQAHvgEAECAZn7d+AAACIKCAAkhGqYmQMgAAA0GgkVE9QNND0R6jamQAGl/X3Va8Wn2hfSjOJButsh4VKrFvolYq1pFU0KgEwxlIJEBBBMSV0+WQFFqFjJu5xip5QZkHUDFAxe2SSDffBe3n1vJH1JvE3fR5XJV8tRyQHJYKA5wQmMEPxdyRThQkM3QqooA=="
  },
  "L two terminal NULs": {
    "tar-zstd": "KLUv/WAADxUEANLEEBiQpxoDSCx/0n75BhlFb3aTElpLa911SwbbCIrAg/lJ6NqAMkTuML7IS2qABKqAAKaY8i09sHaTyzP//h8x/8+wmwIVAP1zFcAHqh4bAFQVyAwc6wHENPKBSsCAykDmAbJjDZg0E6gQBogUIEAB8YbUAJCOW+GnNgCOlcvwBLQ=",
    "tar-bzip2": "QlpoOTFBWSZTWbPogCAAAHpfgMmAQAH3gEAECAZjrd+ACCggAJIRqh6nqDQAABoZqCKSnlAaaG1DTQAGmHb5pugMSeBJMwoXbq+WTYO+VNjqc46IRkDDjWpUoIUYFeWGEwb4aWQFtrfMIlOWSjEWlNHOyEPXuGbX9lwXjmwMU1ekhGOknFYVQaMBD8XckU4UJCz6IAgA"
  },
  "L bytes after NUL": {
    "tar-zstd": "KLUv/WAAD00EAGKFEhmAOenoN0fEFguEjxJwM7Tb3ECWlH4jBiUD2RhQYcnu9AKXlQiSFJoDZNRpAvwROKqsRBHWQQkMZKC7YIJp+ul99/1/s/svIlMJFQD9cxXAB6oeGwBUNZARxuD6axryQPVgQOVAxgHyGAyYNBOoEAaIFCBAAfGG1ACQjlvhpzYAjpXL8AS0",
    "tar-bzip2": "QlpoOTFBWSZTWVvEaKIAAH3fgMuAQAH/AEAECAZn7d+AGCggAJKIUYQMgADQGnqNNBtSCTTIHqHqHpNAAPUx6+79jVYbtHF4rUCU9s/A4zoe7dIzFqLrnCHpDFZzU1FCURkBTDjBIoxHWxwaEpFLEsHPsPGMITr4YgBJ3o5k1xNAzALpXnZjPQn5URgOL0rGoX1IWXiP4u5IpwoSC3iNFEA="
  },
  "L invalid UTF-8": {
    "tar-zstd": "KLUv/WAADzUEANLEERyQp+n///+/iU/fgEkpYkC9rPXevehbAuio6qgM6hVSAg/mR5FajYVDpAj4I9DFCGjADEhgiim3JYR7nTTP/P4/Yv73oNQKFQD9cxXAB6oeGwBUFcgMHOsBxDTygUrAgMpA5gGyYw2YNBOoEAaIFCBAAfGG1ACQjlvhpzYAjpXL8AS0",
    "tar-bzip2": "QlpoOTFBWSZTWY81C4QAAHlfhMmAQEH/AEAECAZird+ACAAIOCAAciNUNMgAAAaBtT1BJImk0ZAyfqJ5RoACefm3Bg/FVtIosEg4YHZMrhPB9yuVgtLIUATL39dxysQVphJTpyqBTZSvYJ76XqMgaEorD5TzcbQkDcMjaWpetei+8Ny2EoJIGIEQQLVKCH4u5IpwoSEeahcI"
  },
  "L truncated UTF-8": {
    "tar-zstd": "KLUv/WAADz0EANIEEh2Qp+n/////v5/32EiASSliQL2s9d69kbXEgaqOyuoREgIP5ieRWhULh0jxeAPQxQZIwAooYIopt6WDe500z/z+P2L+16DUChUA/XMVwAeqHhsAVBXIDBzrAcQ08oFKwIDKQOYBsmMNmDQTqBAGiBQgQAHxhtQAkI5b4ac2AI6Vy/AEtA==",
    "tar-bzip2": "QlpoOTFBWSZTWXIaY+MAAHjfwcmAQAH/AEAECAZird+AEAAQAAg4IAByI1QYg0AADQMnpBJInqjRkMj0T0RoaGgn187eLB+KPeMUUiQS5HhMqxXQusVapFsZCgCZfZSJDiB0wkp4Y0ApsntYJ2YWqLg0HjqEJUL42QQc0ZOYWpesgkPxzUqKMPmCjBmIkvQsEPxdyRThQkHIaY+M"
  },
  "L repeated": {
    "tar-zstd": "KLUv/WAAEU0EAEKFEReAt+kAtxHJX/xPZy3mYa/NfrZqYoB1GYlHU1mUGsQtGBLVWJLFxVIpKp4wiqxAOhZLgGOOuU0lodBL77vv/yN0/x0gIgEXAP0oCoAA+EAFWkBNgBxQhvM/T1ofqCM/qAgYUBnIPEB2rAGTZgIVwgCRAgQoIN6QGgDScSv81AbAsXIZnoAW",
    "tar-bzip2": "QlpoOTFBWSZTWdH+A/gAAJ3fgMmAQAP9AEAECFRird6ACLggAJENKMjQAAA0A0/VAqimoepGhp6j1PSbKejSeo2nOM+nD4TGsKYdaNm8iF3zczJPUTRxhUqiEhJp31vXn1URUkQwZfmwMEm1bSwslWnNitLNxumak+jezZNoxhfpkxVoFtHikJ65RyNXEJQ4BrxAUQNGFCy68In4u5IpwoSGj/AfwA=="
  },
  "L dangling": {
    "tar-zstd": "KLUv/WAAC2UDAOQDa2VlcAAwMDAwNjQ0MDAwMDAwADAwNjYwNgAgMAB1c3RhcgAwLi8uL0BMb25nTGluawAxMDAyNQAgTHNhZmUPAP1BBfKBSsCAyg6Qo2DApJlAhTBApAABCog3pAaAdNwKP7UBcKxchiegBQ==",
    "tar-bzip2": "QlpoOTFBWSZTWUAAS9AAAFbfgMmAQAH3AEAECARjqd4ACCggAHQSomnqaGgA0NNNGglNUAAPUAADTee5H0OcDEgwJDDvyXlIIrKCVmZAI+dzNAUgsFD3sA2WU4LU42GG9NCFDrYcIEvSMDkjKK65/fI0aJMuJlgo/F3JFOFCQQABL0A="
  },
  "L before PAX": {
    "tar-zstd": "KLUv/WAAE2UFAOKGFxxwazMGiN0Jje1VoEMjfeY63Q5p/Ejy9PyvfU8GCzHUsdhqs4c+RKB4tEmBjBKuM1m+NSy7qLcHXUKkhUWo4xIywCcqzMIlmIYbqEQl49PHgfCE7dYe/3+t9o/NrhIaAP1zFcAHqh4bIFQVyDwA6FjmJoB24IHeBfLKwYBqQIdJkK58oBIwoLID5CgYMGkmUCEMEClAgALiDakBIB23wk9tABwrl+EJaAE=",
    "tar-bzip2": "QlpoOTFBWSZTWTXc1h0AAKdfgMuQQAH/AkBESAZ379/ASCgwALihqmho0AAAAAAZBjIZDQaDRoA0ADQwShSbQhkaaPRGQNBoAephfh690WLBQUndeRIYwBK31rOChQBEwtIZAkAlUAYAmZK1g95leSgI4FAQu3bt8YBaoOapkYWFrRVNpC4kQ2s7FHHMDGGi6nDjI9USzwIOBdTT5v0gnG4K2OuzA7nKcGBTToOZUUEWAJ8Y8QFgOhAHRTLQAfxdyRThQkDXc1h0"
  },
  "L after PAX": {
    "tar-zstd": "KLUv/WAAE30FAPKGFxxwazMGiN0Jje1VoEMjfeY63Q5p/Ejy9PyvfU8GCzHUsdhq/9DnEjLAp8IsXIJpuIFKVIIsQh2B4tEmBTJKuM5MlvjWsOyi3h50CZEWxqePA+EJ2609/v9a7R+bXSUbAP1zFcAHqh4bIFQVdAxG6wLENPlAYb9YARhQeQAQCTACJEBMHzxQPxhQOZBxgDyGAKbNBCqEASIFCFBAvCE1AKTjVvipDYBj5TI8AS0=",
    "tar-bzip2": "QlpoOTFBWSZTWY2pXU4AAKdfgMuQQAH/AkBESAZ379/ASCgwALm2GqaGjQAAAAAAyDUagAAAAAAAAqpqKbU9BkQP0gAIaAxpz48/7/tzxfBCyripkxBK6d0WEFopoR5GM8RXAUBholdHWc2SasSqIEmvbt3YAKDgJlARiB/aCQgKECkKGFRJopJLAENH6XtLlPjmNN6EHAvpp947QTngFbHfhgdzpODApp0HMqKCLAEmN9EBnKr7yqnDFodxdyRThQkI2pXU4A=="
  },
  "L repeated across pair": {
    "tar-zstd": "KLUv/WAAFQUFAPIFFBpwadMBAKuqJS9kV/S/qeTAYpO1fOuiqsKRAYlJU4mYnuM2ABbVEBshL8CWHJie4mLJFCF/nCqrkJLFksAojOI2lYhEN73vvv+P0P33gKgEGwD9KAqAAPhABVpATYAcUIbzH5w0PlB1bABQZcATgEA1wIBKJIGKgAGVgcwDZMcaMGkmUCEMEClAgALiDakBIB23wk9tABwrl+EJaAE=",
    "tar-bzip2": "QlpoOTFBWSZTWWdkxTEAAMbfgMmAQAP/AEAMCFRi7d6ACPgwALgMaNGgGTIaMRpoGmBjRo0AyZDRiNNA0wEUk0npQ0D1PU2kbKepmo9Q3qmQa8+7AwkFRytjpYT7BR4YHrLVJJ4CRMx8xuS5RgEhNq1ji8RxoK0SBByNI+JgmTCWt9kklDSzPIi9JbkjdOyVEje3PR0bRMxx99paFhSbO3R2mHXrrzD9DOdzvPxK/0qpOqe1xUK0v4IH+LuSKcKEgzsmKYg="
  },
  "K empty": {
    "tar-zstd": "KLUv/WAAC80DAMIEEBeApeqITELaJFBPYogax6njNw25mxCYDJE1uCIiJU4ChsKCBunoz3XvUO0FVGGKKReuOCB00jzz+/8p5X8FjLkTAP1zFdACamKAOAACOP81aTCgMpB5gOxYAybNBCqEASIFCFBAvCE1AKTjVvipDYBj5TI8AS0=",
    "tar-bzip2": "QlpoOTFBWSZTWR+ZciIAAHFfgMmAQAP9AEAMCFRird6ACKggAHIaUaPUBoAAA0ep6g2lTTFDQMQHqNNNA0ossbLmsyDVUkBdbDIvLEPYKsmA0hnzO+9XSOLAmNAdutK0joyNsKip6IbTnEi3IeueNIgsgLsxyDdBu5gVekQRShCN5SYpbKFO0gPxdyRThQkB+ZciIA=="
  },
  "K NUL-only": {
    "tar-zstd": "KLUv/WAADf0DANJEEBeAJ+rAGkZKgx2dvdDJlhjbhggOmNEhA08tl54ZBWBOKBLJCUbRPGJZG6DVCihQSCHXpXdA9NE88/v/5+R/DUqxFQD9QAVaQZUAuQGyB7jA+ReT9gM1gAGVgcwDZMcaMGkmUCEMEClAgALiDakBIB23wk9tABwrl+EJaAE=",
    "tar-bzip2": "QlpoOTFBWSZTWdhtAAMAAHXfgMmAQAP9AEAMCFRird6ACqggAHIaUaMgANA0GjRo9QSKJlNGg0xDTRoaA0wMu9VjzRGEBzEBZvryVq1icdoUqlAME17zuuLZiCaYkr+mFAKpqVcYX8oFD0y3KUlJvQnQprIwWYC9A0JdFu5AP7l7wqYPI4DJBkwwaVkQ/F3JFOFCQ2G0AAw="
  },
  "K embedded NUL suffix": {
    "tar-zstd": "KLUv/WAADcUEALLFExpwadMBgISOFabXj2n/VssheOUNdeIBUFUVyi0Vplrg1Eh4ACwUW5kkiwHdNQuqIZxufBKkMmtBlIVABujQXaZao+inOOL3/48D/5vIZAIaAIU3VQA0NEAB0JAOVAA00AIqwYMLQBiCB5x/MWnvQFVgQOVAxgHyGAyYNBOoEAaIFCBAAfGG1ACQjlvhpzYAjpXL8AS0",
    "tar-bzip2": "QlpoOTFBWSZTWSIf+DgAAHxfgcuAQAP9gEAMCFRn7d6AAACIqCAAkg0kDQAAAADQPUEkhT1GjIDTamgeoNNAaTL7qa8HDFzQYfjEBXsfO9WKoTS1BFUIBgTL22EpBZFVMkophJcZ84AuDLFre5OtohDSt8U9CEkhmBO+LQLu8CpXHOYWvDvObcKuOmQZqe9jDa4fI0JMmJy9MGmsiH4u5IpwoSBEP/Bw"
  },
  "K two terminal NULs": {
    "tar-zstd": "KLUv/WAADS0EABJFERiQp+mACA2y2j7ajXdq9PfdRkJJUOSuizItDYYtlQLQXSgSyHKAiaD00qPrgRCWgRhW4JhjLsOWIHrpfff9f6Xuv4fMIxYA/SgKgAD4QAVaQE2AHFCG8y8mnQ9UAgZUBjIPkB1rwKSZQIUwQKQAAQqIN6QGgHTcCj+1AXCsXIYnoAU=",
    "tar-bzip2": "QlpoOTFBWSZTWbTxviYAAHdfgMmAQAP9AEAMCFRjrd6ACKggAJKGlAZAAaDQMjRtQSSap6eqDQM1AeoDQNKmHjRcxiD1kPAgL7mwVFaJn1BChAMCZfMaUL7BBYmEl051yAuLKdryUmh9K4TU+Tu8JqUs2kBerAU3cLCWulY6IGfj3hFAnLmBBlHcWpg0KSP4u5IpwoSFp43xMA=="
  },
  "K bytes after NUL": {
    "tar-zstd": "KLUv/WAADa0EAIIFExmAt+mAhAoJHz9+fEoIRoHjapvttN2ECLsyLRWGzTg90hUACWQrk2QhNAfYCE6V8elIZdaCKMuABApUoMuwNYh+et99/1+p++8hkwkaAIU3VQA0NEAB0JAOVAA00AIqwYMLQBiCB5x/MWl5oHowoHIg4wB5DAZMmglUCANEChCggHhDagBIx63wUxsAx8pleAJa",
    "tar-bzip2": "QlpoOTFBWSZTWSGaUYsAAHrfgMuAQAP9AEAMCFRn7d6AGKggAJKImoaPUaAAAAwg0Ekk1PKDQepk0MjQaaA9S8xwpqm4YwZ7FERAV1V4plSJqNYRURdGSHAmXudlhugIIJhJXX83grWWSVDk7g7K8ukrYqAiRhkLrQ4G7zAL1pVuDmARK3JC0sODWsR7OBOhGZowTT61ymTjJI/i7kinChIEM0oxYA=="
  },
  "K invalid UTF-8": {
    "tar-zstd": "KLUv/WAADVUEABKFEhyQp+n///+/sRChQVYbUdAF93Jf6iaUJNDJjBMysTnIIiJNJycAEAy2SBwC0oT+pD5jsJxRWAFTTLmQxePQSfPM7/8rlf81tPYCFgD9KAqAAPhABVpATYAcUIbzLyadD1QCBlQGMg+QHWvApJlAhTBApAABCog3pAaAdNwKP7UBcKxchiegBQ==",
    "tar-bzip2": "QlpoOTFBWSZTWaPs3LkAAHZfhMmAQEP9AEAMCFRird6ACAAIuCAAkoaSNDQAAAGjRo9QSSao3qgyGmIxGg0NA5GPaepj8D65DwICreYqtTiZ9gQoQDAmWWX2ywrgQQmElfhzzArmWel5KTQ991KaZTM0JEil6PAsgLswsPsTux0ffctaIIg0jQZKSZYmDgTYSP4u5IpwoSFH2bly"
  },
  "K truncated UTF-8": {
    "tar-zstd": "KLUv/WAADWUEABIFEx6gpen///8/OvT9NyJ+e8k3Bx3OiLPRTSgJWf2NkAGxOcgiIk0nHxQHBotIHAHShP6kPkOwnEFYAFNMuZDFw9BJ88zv/yuV/y209gIWAP0oCoAA+EAFWkBNgBxQhvMvJp0PVAIGVAYyD5Ada8CkmUCFMECkAAEKiDekBoB03Ao/tQFwrFyGJ6AF",
    "tar-bzip2": "QlpoOTFBWSZTWXUy7P0AAHXfwcmAQAP9AEAMCFRird6AEAAQAAi4IACShpQaAAGgA0aNHpBIoo8oA0zUMhoBoDgdumetn4I4QIzEBZWd1RaBOOoJqaAYJrD7ShZIQSTEldy44gVrWOqMFBzjdbUnJSbmnNErRALIBOYUIFv7reBnyxghkDCa4ZRPmWRg4WoSSP4u5IpwoSDqZdn6"
  },
  "K repeated": {
    "tar-zstd": "KLUv/WAAEVUEAELFERiQp+kAtwuJ22839lOKGTfZtpTkQWackAGJR1NJlCZ0EwCJaizJ4mKC0kQ8SkXWwDgWMwLHHHObSsOhl9533/8vivtvAREJFwD9KAqAAPhABVpATYAcUIbzP09aH6gjP6gIGFAZyDxAdqwBk2YCFcIAkQIEKCDekBoA0nEr/NQGwLFyGZ6AFg==",
    "tar-bzip2": "QlpoOTFBWSZTWYHZ/eUAAJ3fgMmAQAP9AEAMCFRird6ACLggAJIJRTSb1IyDQYNT1GTJp+qBVJT0j1AAMhkDQBbF/bNtSj9Cd3earGRDfui8rNAlNqhQoiEgkevv6xYV0EUJCFzr0qC1Iwtk5gmUaETEsBaAoVWBaykzJG4CKFusiI0Cf2awR3+ZJskp6So2CSuEHDFnR27+BE/i7kinChIQOz+8oA=="
  },
  "K dangling": {
    "tar-zstd": "KLUv/WAAC2UDAOQDa2VlcAAwMDAwNjQ0MDAwMDAwADAwNjYwNgAgMAB1c3RhcgAwLi8uL0BMb25nTGluawAxMDAyNAAgS3NhZmUPAP1BBfKBSsCAyg6Qo2DApJlAhTBApAABCog3pAaAdNwKP7UBcKxchiegBQ==",
    "tar-bzip2": "QlpoOTFBWSZTWY3773gAAFbfgMmAQAH1AEAMCARjqd4ACCggAHQSpqNqA0A00DQaCUUGjQ0eoAANNeH3KRl0kQcICqIM3QpUClg8ciIoCkWYxUGKIDCEJwNEG3Ix7h40aik1tnMFDz0jwbEfIpVL75aSkWQ4kVjD8XckU4UJCN++94A="
  },
  "K before PAX": {
    "tar-zstd": "KLUv/WAAE2UFAOKGFxxgjRoDW5sV17rAmEwOW3gRzWxbCMlEXXEJGUAZKzkUkkqylYg2wIAR6aMEOKnLERVsi2i2WW0TuoVJD6tQyKAuA4/HOI1l4TwWwkpW8jWNIOlWx2bs7/8z2f89u0waAP1zFcAHqh4bIFQVyDwA6FjmJoB24IHeBfLKwYBqQIdJkK58oBIwoLID5CgYMGkmUCEMEClAgALiDakBIB23wk9tABwrl+EJaAE=",
    "tar-bzip2": "QlpoOTFBWSZTWcHHOzgAAKdfgMuQQAH/AkBMSAZ379/ASCgwALm2GqaA0AAAAAAMgajRNAmAIaemoYAjJhAqpqJPQjyJkPIIwnom0jCPUutu69smiL4IVUWp5PEJWVypIKhZMjMeRhGKAmDHNKyL661NbEJUECT427d3gCzgKKYjED8rJEzEUAMDhgdSEpdAIZS1SZVt9TmN3/A5gLaKPN+jk32CjQ67KDN9ov3qFmOYqYnIqAT4poQJii+8onxxkD/F3JFOFCQwcc7OAA=="
  },
  "K after PAX": {
    "tar-zstd": "KLUv/WAAE30FAPKGFxxgjRoDW5sV17rAmEwOW3gRzWxbCMlEXXEJGUAZKzkUkkqyj2gzqMvAI+M0loXzWAgrWQlgFQoNGJE+SoCTuhwRFby2iGab1TahW5j08DWNIOlWx2bs7/8z2f89u0wbAP1zFcAHqh4bIFQVdAxG6wLENPlAYb9YARhQeQAQCTACJEBMHzxQPxhQOZBxgDyGAKbNBCqEASIFCFBAvCE1AKTjVvipDYBj5TI8AS0=",
    "tar-bzip2": "QlpoOTFBWSZTWWMCo3gAAKdfgMuQQAH/AkBMSAZ379/ASCgwALm2GqaA0AAAAAAGQajRNAmAIaemoYAjJhAqpqJPQjyJkPIIwnom0jCPUutu69smiL4IVUWp5PEJWVypIKhZMjMeRhGKAmDHNKyP2utTWxCVBAk+Nu3d4As4CimIxA/CyRMxFADA4YHUhKXQCGUtUmVbfJzGp2BzAXUUe8dnJxuFGh34UGb8RfvULMcxUxORUAkpfoQJii+8onxxkD/F3JFOFCQYwKjeAA=="
  },
  "K repeated across pair": {
    "tar-zstd": "KLUv/WAAFfUEAPKFExiAt+kAtxHJH+PvbuBCJ6u1bmv5orsY4cqJSlOJmJ7jLgASqiG2QSYJS2QyRcXFBKYH+eN0WYSkLJYCRmEUt6k8ILrpfff9f4TuvwbEJRsA/SgKgAD4QAVaQE2AHFCG8x+cND5QdWwAUGXAE4BANcCASiSBioABlYHMA2THGjBpJlAhDBApQIAC4g2pASAdt8JPbQAcK5fhCWgB",
    "tar-bzip2": "QlpoOTFBWSZTWf88kH8AAMbfgMmAQAP/AEAMCFRi7d6ACPgwALgMaNGgGTIaMRpoGmBjRo0AyZDRiNNA0wEUhJlDQPU09EzImaj1D2qYhn18PY3SCo42R2mU7hRw3GGGaQnmJFCnqNyXKMAkJprU4PAd9orakCDidI50BMWEsb5ySUNs8sSL0lsSctk4tSNrc9no2CZDv46S6Ey2jSzm6UDXXPqH6GVLnafiV/pVSlU43FQrbfggf4u5IpwoSH+eSD+A"
  },
  "unsafe L pkg/../hidden": {
    "tar-zstd": "KLUv/WAAD1UEAHLFEhmAty0GaNjiGxvtR6emQVUZxVak5NXJGEUGuxASIovUTyRlrWEgA7zDQyXIWADwpzimFoKOVUACPLxNSQfDYhvTVd/+P1P/LdlVARUA/XMVwAeqHhsAVBV0DKN1/DUN8ED9YEDlQMYB8hgMmDQTqBAGiBQgQAHxhtQAkI5b4ac2AI6Vy/AEtA==",
    "tar-bzip2": "QlpoOTFBWSZTWdvIDacAAH5fgMuAQAH3gEAECAZm7d+ASCggAJIRqmjIDTQAANA09QbSknpNGgGCPQmgBpfl7pqebH2jhMKhAlXVZ4IG1FsHxNhQjUxEEhlebsyZap0JTjQEr8NCRJkeTOj38CUUnpmTBCEFmxbNFEHei/rlzSRqSN19tfmPnyNy4nyUkHODBmFKmBD8XckU4UJDbyA2nA=="
  },
  "unsafe L pkg\\..\\hidden": {
    "tar-zstd": "KLUv/WAAD1UEAHLFEhmQtxkD2NjVSal6UwGp8boVUQr8TWXk7hJkuxAWIlPqJ5bS1jCQQYFYHCxR5gKARwkda4g6WkEJDh78lHUwLLc5XfXv/zP1/5JdFhUA/XMVwAeqHhsAVBV0DKN1/DUN8ED9YEDlQMYB8hgMmDQTqBAGiBQgQAHxhtQAkI5b4ac2AI6Vy/AEtA==",
    "tar-bzip2": "QlpoOTFBWSZTWXmQRlcAAH5fgMuAQAH3gEAECAZm7d+ASCggAJIQhGgYgAA0yDT1BtKRoRoGmj0nqaAAaY9fdt7yY+0eVArECW6/f4IGlEoO40FiMzEQSGTylIkqkJVDQHGvGlImyNzOD1aycUnXRGmQThoxbdknNUYAh6OPT4OA+4NRl26JRP8mguVAJjEmCQkQpSoQH8XckU4UJB5kEZXA"
  },
  "unsafe L /hidden": {
    "tar-zstd": "KLUv/WAADyUEAAJFERiQpxoDSNj6pC2KZGIcPtdNEjZYWuuuWzL7BgmRJ/WTSK6tUktgEMGNLw5kbaFAIyCAKaaMLh0MDyeoqz7+f6b+Y2GXBRUA/XMVwAeqHhsAVBXIDI51/zUNe6AaMKAykHmA7FgDJs0EKoQBIgUIUEC8ITUApONW+KkNgGPlMjwBLQ==",
    "tar-bzip2": "QlpoOTFBWSZTWcQkafUAAHvfgMmAQAHvgEAECAZm7d+ACSggAJKIUxMgyAABpo0zUG1JMhAGNIPKaAwSXnG3cLVeoToFWgSutq+DjeiLr+ZSVo2MIckMaxitL1SdWAqGQEpzekSYhcyVlhJ6TOfRATAipbeEgMYDp75FwG5BrHuOvZ6oLUcECTBISIaE0iP4u5IpwoSGISNPqA=="
  },
  "unsafe L \\hidden": {
    "tar-zstd": "KLUv/WAADyUEAAJFERiAqRoD4Gcis9koBGNcNscgNyssL7gY4cr7CkmRJ/WzSK6tUosgQAQ/3gAgawsNmgEFTDFldCmBeDhBXfXx/zP1Hw+7LBUA/XMVwAeqHhsAVBXIDI51/zUNe6AaMKAykHmA7FgDJs0EKoQBIgUIUEC8ITUApONW+KkNgGPlMjwBLQ==",
    "tar-bzip2": "QlpoOTFBWSZTWTb78BoAAHvfgMmAQAHvgEAECAZm7d+ACSggAJKIUxGgyAAAaNNlBtSTFNGg9T1PUHlGgA0t19zwFku0Odwr0CW6ebwONKKO3yIl6M7CHJDGVKKigcGAiMgK2s9IqxCbJSkVekzn3QEAprOdpAKIAKA5++E4EcB1k9yWNeuDFpBQm0TEzGeOAj+LuSKcKEgbffgNAA=="
  },
  "unsafe L C:hidden": {
    "tar-zstd": "KLUv/WAADzUEADLFERiAqRoDsG+IRWI/UmUFVHyQLCfNA9yEwGR7FJYiU+rpxTLeMtYIAIEiiNCfD7rX1OAZVMAUU0ZjJRAHTlBXffz/TP3Hw64LFQD9cxXAB6oeGwBUNZARxuD9axr1QOVgQOVAxgHyGAyYNBOoEAaIFCBAAfGG1ACQjlvhpzYAjpXL8AS0",
    "tar-bzip2": "QlpoOTFBWSZTWXEXE/8AAHzfgMuAQAH3EEgECAZm7d+ACiggAJIRqmQ0GgAAaAaYg2lKbSaAZM1AeoZAGk7/d2kWKwj0yCqQJXW2+CBqRKGiwZUjMxEEhmMpKSibmBSNAcuc6EiLI2NcHtddZxpScKDoBi1obRypBBrBl743ojKLjtfZ00rQxKDk+HTBwc4SQygh+LuSKcKEg4i4n/g="
  },
  "unsafe L pkg/C:hidden": {
    "tar-zstd": "KLUv/WAAD00EAGKFEhmQpxoDaKhVoyJliUyMQ3xZSUqwTGlUdVQGmxAWIlPq6cRC3jJmDACC09yhCmrxCKF7hmqvoALHHDMi62BI8IK66uP/Z+o/HrsuFQD9cxXAB6oeGwBUNZARxuD5axrxQE1gQGXQ8QB5tAZMmglUCANEChCggHhDagBIx63wUxsAx8pleAJa",
    "tar-bzip2": "QlpoOTFBWSZTWYLeT9gAAH3fgMuAQAH3EEgECAZm7d+AKCggAJIRqjRoBoAA0GgaeoNqSTyJk0eoehNGRoAZhl8qk2bDd34zCoQJS4t5HGxFjlEqJ0UMIckMZyksrFBCUBkB0wx1JF7D97HJoxL54JOmfzehCCXQSp1pIN9GHXLeCdWTuzO2IlPnyJs0KCS+DUDBmEplBD8XckU4UJCC3k/Y"
  },
  "L terminal NUL=false": {
    "tar-zstd": "KLUv/WAAD20EAGKFEx2gpxkD/1lVdfzWX5NGgmzXfv8t7Iwsq5GkVr9BMiohLCJR6ujEIoqFYAOIix1oUjk1/pxjbZBWKyQAGjQfsgdDcpfTVf/+P1P/71CKBRUA/XMVwAeqHhsAVDWQEcbg+Wsa8UBNYEBl0PEAebQGTJoJVAgDRAoQoIB4Q2oASMet8FMbAMfKZXgCWg==",
    "tar-bzip2": "QlpoOTFBWSZTWf+YFHUAAH1flMuAQAH3AEAECAZrrd+AACAIACgoIACSEaoMgaNAABoGJoNpSTT0hoMmQek0AB6kufm2tTY/dOFAqkCV219yBWi+C2GgiipiIJDJ3Tv6uh7lFCURoCWHLIkSZTazi7LCUcqUIDaQxiAqJ06mIcNYMo2qLUun18vTaKOxcUhTGDkD4fNCDuckEPxdyRThQkP+YFHU"
  },
  "K terminal NUL=false": {
    "tar-zstd": "KLUv/WAADVUEAGLFEx6gJ+n/WVX1n0/SWS203Ybs/pqNi73Ntp3IdFANlgErLSoXcgo43HAsUjEahBwgM8HpIX9fmaagLM1BCSBDdlWuhKKf4ojf/08S/C8iJSYUAP1zFdACaoL5giecfzHpeqByMKByIOMAeQwGTJoJVAgDRAoQoIB4Q2oASMet8FMbAMfKZXgCWg==",
    "tar-bzip2": "QlpoOTFBWSZTWS7MLUYAAHlflMuAQAP9AEAMCFRrrd6AACAIAAqoIACSDSTQ0AAANAANNBtKjKZBo0aGhiADQaXLv1qoMC9walmQktdWrwbChDmpSZOJJpDL/mFdaW2YzMCcaAs43QSIsjplks3yKDxxpOESLM4RoUbpaBa4AVoSNg5t03r0cLv388CHw8SzfEf4sFBTa12EQ/F3JFOFCQLswtRg"
  },
  "L terminal NUL=true": {
    "tar-zstd": "KLUv/WAAD3UEAGLFEx6gpxkD/1lVdfzWX5NGgmzXfv8tDI/JUp8ktfoNkgEqMawiUeovFmE0CDtAXOxAk8oFAH/QOdYKabVDEqBB8yGbQCR3OV317/8z9f8OpVgVAP1zFcAHqh4bAFQVdAyj9fw1jXigJjCgciDjAHkMBkyaCVQIA0QKEKCAeENqAEjHrfBTGwDHymV4Alo=",
    "tar-bzip2": "QlpoOTFBWSZTWUpPUj4AAH1flMuAQAH3gEAECAZrrd+AACAIACgoIACSEaoMgyAADQAZNBtKiepkNBp6mQekAAepLn5jYpsfuGFIq0CWyN3coM6L6HaWFaMjEUJDJ3Tv6ul7VUhKoaAlhxxJEmQizg9VpKCTqeM/AHSzlkmUchsxYwhZuSi5d94cRludfsERIMGpHw+YEna2YEPxdyRThQkEpPUj4A=="
  },
  "K terminal NUL=true": {
    "tar-zstd": "KLUv/WAADb0EAFKFEx2gJ+n/WVX1n0/SWS203YZsfWGGxA7yyU5kOqgGy20lTDVkCsA0HAvFGA2CGpw7gSlCj4hVlgKSLAckcO7cZaolFN00z/z+f0r5X8RaShoAhTdVADQ0QAHQkA5UADTQAirBgwtAGIIHnH8x6XqgcjCgciDjAHkMBkyaCVQIA0QKEKCAeENqAEjHrfBTGwDHymV4Alo=",
    "tar-bzip2": "QlpoOTFBWSZTWbsy28sAAHlflMuAQAP9AEAMCFRrrd6AACAIAAqoIACSDSQNAAAADI0DQSKp6amnqGgyaNBoANBpad+tVCvVzmZCcQGqqrwq1QJ16QkpIBgmrvl9lgbJxBOmJLfxtmBZWo0wwNm2FMJR0LdhUW3SNEdOTYLfECw+QQHUKc3UyF4J77B4A+SzfEz8WHo9cWu0iH4u5IpwoSF2ZbeW"
  },
  "L+K reverse=false": {
    "tar-zstd": "KLUv/WAAEQUFAKKFEheAJ+rAWvw/G2zWTW85jyVGI9mCA2Z0yIcUYLJIKPcWc+phEZAeU0Bk7RiURJrnjWkzCIkZhhTAguU69Q6ITppnfv8fofzvsVYLHQD9QIUxoMIFUMAHFAidRCrw4IIQBjCCBjBPFAkqAG4r5WFAJeBdCFCFCyAmDgZUBh0PkEdrwKSZQIUwQKQAAQqIN6QGgHTcCj+1AXCsXIYnoAU=",
    "tar-bzip2": "QlpoOTFBWSZTWb4TnO4AAKTfgMuAQAP9AEAMCFRird6AHKgwALawSlRgmAJgAEwam9QSmop5GoYjZIGgNAASpqNE2gJkaNoAjGgxbLrOlv5MmjF0UZqgZik5uyDALAFgtbEgkKUIAIGzndNGrQ/IPo1gCmAgCi8yxWAXCCBe9yTYvVHkoXhxdUEIudWCsKy05kGLkl4lmBsPHvkbMzkaBbddpmDAfIzBgL6FBsUL4FRXrBE8F3JFOFCQvhOc7g=="
  },
  "L+K reverse=true": {
    "tar-zstd": "KLUv/WAAER0FALJFExlwSdQBQJmQl4Uh8IpNJQc23gjJWoeqqkcGhxSZBCyUMyCyhiAk0gB6izn1sJQBKTpvjmk7CokdhyTAguU69RKKTppnfv/fMPK/iLVaHQBjHaPCBVAwBlS4AAr4gAKh05wKPLgghAGMoAGIiTaBCi7APJkwoBLwrh5QHTCgciDjAHkMBkyaCVQIA0QKEKCAeENqAEjHrfBTGwDHymV4Alo=",
    "tar-bzip2": "QlpoOTFBWSZTWe9Aib8AAKTfgMuAQAP/AEAMCFRird6AHKgwAK2wSik9TynqGgHpNGIaeo09R+qCVT0U9GgEwmARowJgSpqNJp6CYAaCNMmExek8eUtjKio99T1HQBEJcSUwsCsBbM+9CIRFKEAEDbjrlo1aGiDqNYApgIAoxMviwD2IDD0tQYLRaxqp0oDF4PDqkaCRjSQ+DHCVEuEtvJkCrIcdzIzA1uM91CgRKy6gMowOGDrpZGhzET+LuSKcKEh3oETfgA=="
  },
  "L state clears at member": {
    "tar-zstd": "KLUv/WAAF40EAHJFEhiAtxoDaPbz5ARtgqygcywkiRGmgKVJGDIvOVIaLTJghVSpq4QZ694hWrEKPjwCYHOCRbi3AsccMxrsICB4QV318f8z9R+L3RYYAP1zFbAP/OMMqBjMuA+o9NgAoKpAZnCs+69p2APVgAGVgcwDZMcaMGkmUCEMEClAgALiDakBIB23wk9tABwrl+EJaAE=",
    "tar-bzip2": "QlpoOTFBWSZTWd0Nun0AAMdfgMuAQAH/gEAECAZird+ACWgwAKyCSlPSbKZNNHqaBo2o9Q9E9Qw0MmQMjEGJk0NMCKSnpNNDQGjRpkAAxI/S3AYlQO/plbGoeIS5YDuMkNRcI5mrX0giSVCZYUJAkJ9/WlodTg0pddJBqSBBvw5kpglBCUG6G+DfBYWJhjWCRPFSkmeo3F5ErEaGaMSeh7IjBpIYP/SJnxZk4bC0eORQuRRDqFEOHEL0g/i7kinChIbobdPo"
  },
  "K state clears at member": {
    "tar-zstd": "KLUv/WAAExUFAAKGFBpgadQBmFqv5w2a3SrQSj51sWOb5Q8sIIhyZAEBOgbWCrm0xVPqZeLWQ6bp4AjAYrkmawTThP6kKuyAJKwhg8M4jOvWWxTdFEf8/r9S+N9EphIbAP1zFRgDKg0isAbmqegDdcaAesDjwYCZslpATYAcUIbzLyadD1QCBlQGMg+QHWvApJlAhTBApAABCog3pAaAdNwKP7UBcKxchiegBQ==",
    "tar-bzip2": "QlpoOTFBWSZTWb41VhAAAMBfgMmAQAP/gEAMClRurd6ACLgwALmhjTQaAGTQGRpoYmjBoVM1MAAAAAACSVPRHqAA9TINNGmmjNNSsLi3TyGCSHefjiZ4gUOMGhchkbBDObck9D0CYEMiy/GNJSFDxJPQwgXixvXqcEVBkFCT8hA0QIwDutOIggUQv/obBA1PBkbDEKBCtLpVeYWDh5MTlpgODHrcWhEK4z5zURRJhpIcb0UGbGSZ8OaS/i7kinChIXxqrCA="
  },
  "blocked 3": {
    "tar-zstd": "KLUv/WAACUUDAMQDa2VlcAAwMDAwNjQ0MDAwMDAwADAwNjYwNgAgMAB1c3RhcgAwLlxwa2cvL3NwZWNpYWwAMDEwMzUzACAzDwD9QQXAgMpA5gGyYwmYKhOoGwaI1CBABfGG1ACQjlvhpzYAjpXL8AS0",
    "tar-bzip2": "QlpoOTFBWSZTWd3IbQQAAE9bgMmAQAHvABAEaqxeAAioIAB0EqAQDQbU0GhoJRQ9TTTTTQAA023fBZpSpQwCSbkkPBYI4cCKApPjCTAjCwUIjRRKLyCMxJPNHMtGLEWdeHc6DBdK1f7A+3aTqOKkQPxdyRThQkN3IbQQ"
  },
  "blocked 4": {
    "tar-zstd": "KLUv/WAACUUDAMQDa2VlcAAwMDAwNjQ0MDAwMDAwADAwNjYwNgAgMAB1c3RhcgAwLlxwa2cvL3NwZWNpYWwAMDEwMzU0ACA0DwD9QQXAgMpA5gGyYwmYKhOoGwaI1CBABfGG1ACQjlvhpzYAjpXL8AS0",
    "tar-bzip2": "QlpoOTFBWSZTWVid234AAE9bgMmAQAHvABAEaqxeAAioIAB0EqCZAA09TQaHqCU1Q9IA0AADXamxfNKiRwGi/AigFU0CAMgEfbxucGcaDBEeMJYwZFMCUBIusHNEadeHc6DhtFWHsT7d5NSoUyA/F3JFOFCQWJ3bfg=="
  },
  "blocked 6": {
    "tar-zstd": "KLUv/WAACUUDAMQDa2VlcAAwMDAwNjQ0MDAwMDAwADAwNjYwNgAgMAB1c3RhcgAwLlxwa2cvL3NwZWNpYWwAMDEwMzU2ACA2DwD9QQXAgMpA5gGyYwmYKhOoGwaI1CBABfGG1ACQjlvhpzYAjpXL8AS0",
    "tar-bzip2": "QlpoOTFBWSZTWTaleYIAAE9bgMmAQAHvABAEaqxeAAioIAB0EqanogAD1NBoaCUUPSAZAZANIytes0pUoYBKjkgWAtyOHAigKT4g9gRhAcMyjjXCDrjRTayDPrFQZDrw7jIoElOcPaT7dSMx5MxA/F3JFOFCQNqV5gg="
  },
  "GNUDumpDir": {
    "tar-zstd": "KLUv/WAACY0DAEIEDhWQOR1YIyrVjyXLLvdRss1trs3dJcgVTDHRwUVEvYUhjUjsKO4MtQ64bGiJ0k3zzO//n5P/XSmpEwD9QQX8ATIFAEjHrXFB5mAFgfOCBrsIgAdoZALVwgCRBgQoIN6QGgDScSv81AbAsXIZnoAW",
    "tar-bzip2": "QlpoOTFBWSZTWV/yarIAAE/fgMmAQAHngAQAgARuqN4gCKggAHQSqaekZAAyAA9QSiQaA9RoAACXWZl+SJR0gCM25Y6gHVI8eCKAp95s0IPBHDAkIxQkLmwZZBpfGZHIkrKZQ8OLYdCDOVXd84/o89UUVS68D8XckU4UJBf8mqyA"
  },
  "GNUDumpDir payload": {
    "tar-zstd": "KLUv/WAAC+0DAKLEDxeAJ+pgGxK0IdIdbuKYgi3hROlwbkJgMtkOR6UKRgPGDLilmF5iJTbIZSDcFZC64q7DEK2P4ojf/ycE/6syURUA/UEF7oFa/AEyBQBIx624+RBCXmEFgfOCBrsIgAdoZALVwgCRBgQoIN6QGgDScSv81AbAsXIZnoAW",
    "tar-bzip2": "QlpoOTFBWSZTWc4WJDMAAFVfgMmAQAHvgAQAgARuqP4gCCggAHIakaNGmmJpoxBoaeglEaTSMnppNHtUaAZLtb8lN4vBC4EStPRXPEISoYF4iKApvt4rppMEmKCDvEQwayvR5ZtJmnFoQ4wC34fLa3wYX3ySbEoFMvTUPmCH5ENHAwqLuSKcKEhnCxIZgA=="
  }
};
