// Regenerate compressed bytes with archive-wasm/examples/archive-codec-fixtures.rs.
import { tarFixture } from "./archive-fuzz.js";

export function codecSmallTar(): Buffer {
  return tarFixture([{ path: "value.txt", mode: 0o600, body: "actual codec and complete container checks\n" }]);
}

export function codecLargeTar(): Buffer {
  return tarFixture([{ path: "value.txt", mode: 0o600, body: Buffer.alloc(8 * 1024 * 1024 + 1) }]);
}

export const archiveCodecFixtures = [
  {
    kind: "tar-bzip2", id: 1,
    small: "QlpoOTFBWSZTWXCfp4wAAEZbgsqQQAFrgACAbm/fQAEACAggAHQrEajQyBpoANoglEQyAAANAIP+VQdEIDYLIUStjQFDlmDtssyt9qiPvYIYtBRL0gyJkqkZI5byEQ5+kdeXhwi0RQbB+JgIx6Ond0bUxvnReoB+LuSKcKEg4T9PGA==",
    large: "QlpoOTFBWSZTWfMQTHQBATRbgNiAQAFngACAYgQfUAAIIAB1CU0SAGnqBoBUqNBNNBkxPJxnaSBAF1CIIA14pnrdpTJEAwAAgXOkM0VcYnegQlRVREu5abdi9r1WtvHkQQB2LuSKcKEh5iCY6A==",
    empty: "QlpoORdyRThQkAAAAAA=",
    zeroPadding: "QlpoOTFBWSZTWXCfp4wAAEZbgsqQQAFrgACAbm/fQAEACAggAHQrEajQyBpoANoglEQyAAANAIP+VQdEIDYLIUStjQFDlmDtssyt9qiPvYIYtBRL0gyJkqkZI5byEQ5+kdeXhwi0RQbB+JgIx6Ond0bUxvnReoB+LuSKcKEg4T9PGEJaaDkxQVkmU1nPwrCnAACBQADAAAAIIAAwgCppUAWYBxdyRThQkM/CsKc=",
    prefix1: "QlpoOTFBWSZTWUvFEB4AAAAAgAEAIAAhGEaC7kinChIJeKIDwA==",
    rest1: "QlpoOTFBWSZTWT+RuQsAAC/bgsqQQAFrgACAbm/eQAEACAggAHQrEajQyBp6gAzUEoiGQaAAGgIv+VQdIIDYrMVTtlQFDpmLt89Cx9yiPwYIZNBhN0k5DJipNYNiQiHP0zry8OSPEaDYPxOCjo0gt3RvpjepIAfi7kinChIH8jchYA==",
    prefix511: "QlpoOTFBWSZTWURM4gYAACTbgMqAQAFrgACAYgQfQBAAIABUU0aANAHqBiEmgaeoaaF6hgV2oGtXoUAutH2QMWYES5DPxaJowxOLqIDgHoz+LuSKcKEgiJnEDA==",
    rest511: "QlpoOTFBWSZTWS3XpOIAAAlRgsAQQAAub94AAQAACCAAQRkp6mJp6genqhQNNDIyYiDO7MEWFXrvPNtKYJI6rVsexmbkrD08BSuHifGH4u5IpwoSBbr0nEA=",
    prefix512: "QlpoOTFBWSZTWdqXQOAAACTbgMqAQAFrgACAYgQfQAgAIABUU0aANAHqBiEmgaeoaaF6hgV2oGtXoUAutH2QMWYES5DPxaJowxOLqIDgHoz+LuSKcKEhtS6BwA==",
    rest512: "QlpoOTFBWSZTWbmlV3IAAA9RgsAQQAAub94AAQAACCAAQQ0p6mmJ6RmnqFA00MjJiFUZkVE1TWLXOzDgBcTulcvePADVpZ1MGzPEovBdyRThQkLmlV3I",
    prefix513: "QlpoOTFBWSZTWbDC5lQAACVbgMqAQAFrgACAYgQfQAgAIABUU0aANAD1BiEmhpp6gNHdQwK6UDWr0KAXOj2QMXYES5DPveJow9n7HFEB0B8Z/F3JFOFCQsMLmVA=",
    rest513: "QlpoOTFBWSZTWRHadKoAABPRgsAQQAAub94AAQAACCAAQNGqepptTEZpoUDTQyMmJKAkIBqmsP7G7dKqpMbp5lntlVmpgsk4ly14CcF3JFOFCQEdp0qg",
  },
  {
    kind: "tar-zstd", id: 2,
    small: "KLUv/QRIJQMAkgUSF5DFOYBIFnqpD5xlKTMz0985+dKdEjEFDliSeuQtTQhuUnm6ihZF5Z2El3pUHsK2iffCZc0/fzDG75so7vv+zf97AytoQwgICQCMDvwFAcqKN6QGgOQBJOBhgDEYzk0ACaFHE7Q=",
    large: "KLUv/QRITAIA5AJ2YWx1ZS50eHQAMDAwMDYwMAAwADAAMDAwNDAxADAwNzYwNQAgMAB1c3RhcgAwCQCQ/pAD8YbUAJAOVtx8F4gCBgbDuQkgAQIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAAIAEAACABAAAgAQAANAAADr4uk9",
    empty: "KLUv/SQAAQAAmenYUQ==",
    zeroPadding: "KLUv/QRIJQMAkgUSF5DFOYBIFnqpD5xlKTMz0985+dKdEjEFDliSeuQtTQhuUnm6ihZF5Z2El3pUHsK2iffCZc0/fzDG75so7vv+zf97AytoQwgICQCMDvwFAcqKN6QGgOQBJOBhgDEYzk0ACaFHE7QotS/9BEhVAAAQAAABAPx/HWAB87Ps9g==",
    prefix1: "KLUv/QRICQAAdsF+8UE=",
    rest1: "KLUv/QRIFQMAgoURFqA5BwBI1ptk9eekpP8Bv/8yPBUoWAoGGJJq5C1NB25SebqKlETlnYSXelQewraJ98JlzT9fMMXveyDu+/7N/3uXDbQhDAkAjA78BQHKijekBoDkASTgYYAxGM5N4AhSjk2Y",
    prefix511: "KLUv/QRIJQIA1AJ2YWx1ZS50eHQAMDAwMDYwMAAwADAAMDUzADAAMDA3NjEwACAwAHVzdGFyADAIAA+ggHhDagBIHkACHgYYg+HcBJCXi3hg",
    rest511: "KLUv/QRIrQEA1AIAYWN0dWFsIGNvZGVjIGFuZCBjb21wbGV0ZSBjb250YWluZXIgY2hlY2tzCgABAI3uB2XfbWTn",
    prefix512: "KLUv/QRIJQIA1AJ2YWx1ZS50eHQAMDAwMDYwMAAwADAAMDUzADAAMDA3NjEwACAwAHVzdGFyADAIABCggHhDagBIHkACHgYYg+HcBJDNnTQI",
    rest512: "KLUv/QRIpQEAxAJhY3R1YWwgY29kZWMgYW5kIGNvbXBsZXRlIGNvbnRhaW5lciBjaGVja3MKAAEAjO4HZdoemFg=",
    prefix513: "KLUv/QRILQIA5AJ2YWx1ZS50eHQAMDAwMDYwMAAwADAAMDUzADAAMDA3NjEwACAwAHVzdGFyADBhCAAQoIB4Q2oASB5AAh4GGIPh3ASQWPHbRQ==",
    rest513: "KLUv/QRInQEAtAJjdHVhbCBjb2RlYyBhbmQgY29tcGxldGUgY29udGFpbmVyIGNoZWNrcwoAAQCL7gdlZMafZA==",
  },
] as const;
