export const GUEST_FILESYSTEM_CREATE_STAGING_PYTHON = [
  "def create_staging_dir(parent_fd):",
  "    # This helper guarantees descriptor-relative confinement and no-replace",
  "    # publication, not content integrity against same-UID peers; they can",
  "    # also rewrite the destination immediately after publication.",
  "    prefix = '.openclaw-create-'",
  "    for _ in range(128):",
  "        candidate = prefix + secrets.token_hex(6)",
  "        try:",
  "            os.mkdir(candidate, 0o700, dir_fd=parent_fd)",
  "        except FileExistsError:",
  "            continue",
  "        created_identity = entry_identity(os.lstat(candidate, dir_fd=parent_fd))",
  "        staging_fd = None",
  "        try:",
  "            staging_fd = open_dir(candidate, dir_fd=parent_fd)",
  "            if not same_identity(created_identity, os.fstat(staging_fd)):",
  "                raise OSError(errno.ESTALE, 'create staging directory changed', candidate)",
  "            return candidate, staging_fd",
  "        except Exception:",
  "            if staging_fd is not None:",
  "                os.close(staging_fd)",
  "            try:",
  "                current = os.lstat(candidate, dir_fd=parent_fd)",
  "                if same_identity(created_identity, current):",
  "                    os.rmdir(candidate, dir_fd=parent_fd)",
  "                    os.fsync(parent_fd)",
  "            except FileNotFoundError:",
  "                pass",
  "            raise",
  "    raise RuntimeError('failed to allocate sandbox create staging directory')",
].join("\n");

export const GUEST_FILESYSTEM_RENAME_NO_REPLACE_PYTHON = [
  "def rename_no_replace(src_parent_fd, src_basename, dst_parent_fd, dst_basename):",
  "    import stat",
  "    source = os.lstat(src_basename, dir_fd=src_parent_fd)",
  "    kind = stat.S_IFMT(source.st_mode)",
  "    expected = (source.st_dev, source.st_ino, kind)",
  "    def verify(parent_fd, basename, links):",
  "        current = os.lstat(basename, dir_fd=parent_fd)",
  "        if (current.st_dev, current.st_ino, stat.S_IFMT(current.st_mode)) != expected:",
  "            raise OSError(errno.ESTALE, 'no-replace publication identity changed', basename)",
  "        if kind == stat.S_IFREG and current.st_nlink != links:",
  "            raise OSError(errno.ESTALE, 'no-replace publication link count changed', basename)",
  "    libc = ctypes.CDLL(None, use_errno=True)",
  "    is_linux = sys.platform.startswith('linux')",
  "    if is_linux:",
  "        rename_fn = getattr(libc, 'renameat2', None)",
  "        flags = 1  # RENAME_NOREPLACE",
  "    elif sys.platform == 'darwin':",
  "        rename_fn = getattr(libc, 'renameatx_np', None)",
  "        flags = 0x00000004  # RENAME_EXCL",
  "    else:",
  "        rename_fn = None",
  "    if rename_fn is not None:",
  "        rename_fn.argtypes = [ctypes.c_int, ctypes.c_char_p, ctypes.c_int, ctypes.c_char_p, ctypes.c_uint]",
  "        rename_fn.restype = ctypes.c_int",
  "        result = rename_fn(",
  "            src_parent_fd,",
  "            os.fsencode(src_basename),",
  "            dst_parent_fd,",
  "            os.fsencode(dst_basename),",
  "            flags,",
  "        )",
  "        if result == 0:",
  "            return",
  "        error_code = ctypes.get_errno()",
  "        unsupported_codes = {errno.ENOSYS, errno.EINVAL, errno.ENOTSUP}",
  "        if hasattr(errno, 'EOPNOTSUPP'):",
  "            unsupported_codes.add(errno.EOPNOTSUPP)",
  "        if not is_linux or error_code not in unsupported_codes:",
  "            raise OSError(error_code, os.strerror(error_code), dst_basename)",
  "    elif not is_linux:",
  "        raise OSError(errno.ENOSYS, 'atomic no-replace rename is unavailable')",
  "    # Only a definitive rejection of the fixed flags reaches this fallback.",
  "    if kind not in (stat.S_IFDIR, stat.S_IFREG):",
  "        raise OSError(errno.EINVAL, 'no-replace fallback requires a file or directory', src_basename)",
  "    verify(src_parent_fd, src_basename, 1)",
  "    try:",
  "        os.lstat(dst_basename, dir_fd=dst_parent_fd)",
  "    except FileNotFoundError:",
  "        pass",
  "    else:",
  "        raise FileExistsError(errno.EEXIST, os.strerror(errno.EEXIST), dst_basename)",
  "    if kind == stat.S_IFDIR:",
  "        verify(src_parent_fd, src_basename, 1)",
  "        # A directory rename can replace only an EMPTY directory raced into",
  "        # the absent target. Non-empty directories and files are refused.",
  "        # The slash enforces source directory type at the syscall, even if",
  "        # a peer substitutes a file/symlink after verification. Identity",
  "        # checks are not compare-and-swap; verify publication afterward.",
  "        try:",
  "            os.rename(src_basename + '/', dst_basename, src_dir_fd=src_parent_fd, dst_dir_fd=dst_parent_fd)",
  "        except OSError as error:",
  "            # ENOTDIR can describe the slash-checked source, not just the target.",
  "            if error.errno == errno.ENOTDIR:",
  "                verify(src_parent_fd, src_basename, 1)",
  "            if error.errno in (errno.ENOTEMPTY, errno.ENOTDIR, errno.EEXIST):",
  "                raise FileExistsError(errno.EEXIST, os.strerror(errno.EEXIST), dst_basename) from error",
  "            raise",
  "        verify(dst_parent_fd, dst_basename, 1)",
  "        return",
  "    os.link(",
  "        src_basename,",
  "        dst_basename,",
  "        src_dir_fd=src_parent_fd,",
  "        dst_dir_fd=dst_parent_fd,",
  "        follow_symlinks=False,",
  "    )",
  "    # Only this exact two-name interval permits nlink=2. Never roll back the",
  "    # target on failure: it may be the only remaining link to the source.",
  "    verify(dst_parent_fd, dst_basename, 2)",
  "    verify(src_parent_fd, src_basename, 2)",
  "    os.unlink(src_basename, dir_fd=src_parent_fd)",
  "    verify(dst_parent_fd, dst_basename, 1)",
].join("\n");

export const GUEST_FILESYSTEM_CREATE_EXCLUSIVE_PYTHON = [
  "def create_exclusive(parent_fd, basename, stdin_buffer):",
  "    staging_fd = None",
  "    staging_name = None",
  "    temp_fd = None",
  "    temp_inode = None",
  "    temp_name = 'payload'",
  "    try:",
  "        try:",
  "            os.lstat(basename, dir_fd=parent_fd)",
  "        except FileNotFoundError:",
  "            pass",
  "        else:",
  "            raise FileExistsError(errno.EEXIST, os.strerror(errno.EEXIST), basename)",
  "        staging_name, staging_fd = create_staging_dir(parent_fd)",
  "        temp_fd = os.open(temp_name, WRITE_FLAGS, 0o600, dir_fd=staging_fd)",
  "        temp_inode = inode_identity(os.fstat(temp_fd))",
  "        while True:",
  "            chunk = stdin_buffer.read(65536)",
  "            if not chunk:",
  "                break",
  "            write_all(temp_fd, chunk)",
  "        # exclusive create payload is durable before publication",
  "        os.fsync(temp_fd)",
  "        # Publish with no-replace rename or the checked file fallback.",
  "        rename_no_replace(staging_fd, temp_name, parent_fd, basename)",
  "        target_stat = os.lstat(basename, dir_fd=parent_fd)",
  "        if temp_inode != inode_identity(target_stat):",
  "            raise OSError(errno.ESTALE, 'exclusive publication source changed', basename)",
  "        os.fsync(parent_fd)",
  "    finally:",
  "        if temp_fd is not None:",
  "            os.close(temp_fd)",
  "        if staging_fd is not None:",
  "            # Cleanup stays relative to the private pinned directory, so a",
  "            # parent-path substitution cannot redirect payload deletion.",
  "            payload_removed = False",
  "            try:",
  "                current_payload = os.lstat(temp_name, dir_fd=staging_fd)",
  "                # Preserve ambiguous or partially published link pairs.",
  "                if temp_inode == inode_identity(current_payload) and current_payload.st_nlink == 1:",
  "                    os.unlink(temp_name, dir_fd=staging_fd)",
  "                    payload_removed = True",
  "            except FileNotFoundError:",
  "                payload_removed = True",
  "            staging_identity = entry_identity(os.fstat(staging_fd))",
  "            os.close(staging_fd)",
  "            staging_removed = False",
  "            if staging_name is not None and payload_removed:",
  "                try:",
  "                    current_staging = os.lstat(staging_name, dir_fd=parent_fd)",
  "                    if same_identity(staging_identity, current_staging):",
  "                        os.rmdir(staging_name, dir_fd=parent_fd)",
  "                        staging_removed = True",
  "                except FileNotFoundError:",
  "                    pass",
  "            if staging_removed:",
  "                os.fsync(parent_fd)",
].join("\n");
