export {
  FsSafeError,
  categorizeFsSafeError,
  type FsSafeErrorCategory,
  type FsSafeErrorCode,
  type FsSafeErrorDetails,
} from "./errors.js";
export {
  DEFAULT_ROOT_MAX_BYTES,
  root,
  type DenyMutationPolicy,
  type HardlinkPolicy,
  type RenameIdentityPolicy,
  type OpenResult,
  type ReadResult,
  type Root,
  type RootAppendOptions,
  type RootCopyOptions,
  type RootCreateJsonOptions,
  type RootCreateOptions,
  type RootDefaults,
  type RootMkdirOptions,
  type RootMoveOptions,
  type RootOpenOptions,
  type RootOpenWritableOptions,
  type RootOptions,
  type RootReadOptions,
  type RootRemoveOptions,
  type RootWriteJsonOptions,
  type RootWriteOptions,
  type RootWalkDataEntry,
  type RootWalkDataEntryKind,
  type RootWalkDirectoryErrorBehavior,
  type RootWalkEntry,
  type RootWalkEntryFilter,
  type RootWalkEntryFilterResult,
  type RootWalkEntryKind,
  type RootWalkLimitBehavior,
  type RootWalkOptions,
  type RootWalkSymlinkPolicy,
  type SymlinkPolicy,
  type WritableOpenMode,
  type WritableOpenResult,
} from "./root.js";
export type { ContainmentGuarantee } from "./containment.js";
export {
  configureFsSafePython,
  configureFsSafeNative,
  getFsSafeNativeConfig,
  type FsSafePythonConfig,
  type FsSafeNativeConfig,
  type FsSafeNativeMode,
} from "./native-config.js";
export {
  writeExternalFileWithinRoot,
  type ExternalFileWriteOptions,
  type ExternalFileWriteResult,
} from "./output.js";
export {
  configureFsSafeLocks,
  getFsSafeLockConfig,
  type FsSafeLockConfig,
} from "./lock-config.js";
