export {
  DEFAULT_ROOT_MAX_BYTES,
  openLocalFileSafely,
  readLocalFileSafely,
  resolveOpenedFileRealPathForHandle,
  root,
  type DenyMutationPolicy,
  type HardlinkPolicy,
  type MutationSymlinkPolicy,
  type RenameIdentityPolicy,
  type OpenResult,
  type ReadResult,
  type Root,
  type RootAppendOptions,
  type RootCopyOptions,
  type RootCopySource,
  type RootCreateJsonOptions,
  type RootCreateOptions,
  type RootDefaults,
  type RootMkdirOptions,
  type RootMoveOptions,
  type RootOpenOptions,
  type RootOpenWritableOptions,
  type RootOptions,
  type RootReadOptions,
  type RootRemoveOptions,
  type RootWriteJsonOptions,
  type RootWriteOptions,
  type SymlinkPolicy,
  type WritableOpenMode,
  type WritableOpenResult,
} from "./root-impl.js";
export type { RootCopyPublicationReceipt } from "./copy-publication.js";
export type { CopyCloneMode } from "./copy-policy.js";
export type { ContainmentGuarantee } from "./containment.js";
export type {
  RootWalkDataEntry,
  RootWalkDataEntryKind,
  RootWalkDirectoryErrorBehavior,
  RootWalkEntry,
  RootWalkEntryFilter,
  RootWalkEntryFilterResult,
  RootWalkEntryKind,
  RootWalkLimitBehavior,
  RootWalkOptions,
  RootWalkSymlinkPolicy,
} from "./root-walk.js";
